### PR TITLE
Add the OsmSharp.IO.API project

### LINKED ISSUE #2: Bring in OsmApiClient
Hi @xivk,

I see that this repo isn't very maintained.
@blackboxlogic and I are working on the following project together which I think is similar:
[OsmApiClient](https://github.com/blackboxlogic/OsmApiClient)
I think it might be beneficial to bring it in under the umbrella of OsmSharp, what do you think?
I'm using it in production for a while now which great success.
Please let me know how you would like to proceed with this.
Generally speaking, the maintenance of this will still be with @blackboxlogic and myself so besides the initial setup I don't see any work from you end.

I'm a maintainer in this organization, but I don't have the permissions to create a new repo or assign the relevant permissions in order to add secrets for example to publish nuget packages (I think).

### PR DESCRIPTION
**Pull request by HarelM**
Currently without deleting the old one, but this should be part of this PR discussion.
Merging this will resolve #2.
There's also a need to better define the name of the DLL, namespace, package etc.
There's probably more to do here.
@blackboxlogic feel free to push directly to this branch.
@xivk any input would be welcome here.

### CODE REVIEW

**Comment by HarelM** [comment]
@xivk @blackboxlogic any feedback on this?

**Comment by blackboxlogic** [comment]
There might be some value in maintaining git history (pull from the other repo) instead of just pasting the code in.
Would be nice for the package name, project name, repo name and namespace to match. That can probably be fixed later?

**Comment by HarelM** [comment]
I don't see a lot of value in the history as the classes are pretty straightforward...

**Comment by HarelM** [comment]
I agree about unifying in general, can be done in a layer step though.

**Comment by blackboxlogic** [comment]
That's fine. Go for it.

**Comment by HarelM** [comment]
Should I remove the old code? I have a problem with throwing stuff away...

**Comment by xivk** [comment]
No problem for me to remove the old stuff. Is there still a branch with the old stuff left then?

**Comment by HarelM** [comment]
This isn't merged yet, I'll create a branch for the old code and remove it as part of this PR.

**Pull request merged**
